Models/ErrorViewModel.cs
namespace Pc1Laboratorio.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Registro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;//AGREGAR 

namespace Pc1Laboratorio.Models
{
    public class Registro
    {
        [Required]
        [Display(Name ="First Name",Prompt ="Enter the first Name of the student to be registered")]
        public string? name {get;set;}

        [Required]
        [Display(Name ="Last Name",Prompt ="Enter the Last Name of the student")]
        public string? LastName {get;set;}

        [Required]
        [Display(Name ="Course")]
        public Course?  CourseName {get;set;}
        public List<Course>? Courses {get;set;} 
    
    }

    public class Course
    {
        public string? id {get;set;}
        public string? type {get;set;}

        public bool active {get;set;}
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Pc1Laboratorio.Models;

namespace Pc1Laboratorio.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RegistroAlumnoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Pc1Laboratorio.Models;//AGREGAR SIEMPRE

namespace Pc1Laboratorio.Controllers
{
    
    public class RegistroAlumnoController : Controller
    {
        private readonly ILogger<RegistroAlumnoController> _logger;

        public RegistroAlumnoController(ILogger<RegistroAlumnoController> logger)
        {
            _logger = logger;
        }

        public IActionResult VistaRegistro()
        {
            return View("VistaRegistro");
        }

        [HttpPost]

        public IActionResult registrar(Registro objRegistro) //crear un c# class "Registro"
        {
            string? nombre,apellido,cursos=null;
            int credito=3,precioCredito=100;
            double precTotalCursos=0,IGV,total;
            
            nombre=objRegistro.name;
            apellido=objRegistro.LastName;
            List<Course>curso=objRegistro.Courses;

            for (int i = 0; i < curso.Count; i++){
                if(curso[i].active == true){
                    cursos += curso[i].type+" ";
                    precTotalCursos += (credito * precioCredito);
                }
            }

            IGV=precTotalCursos*0.18;
            total=IGV+precTotalCursos;

            ViewData["Message"]="⇛ Nombre del alumno:"+nombre;
            ViewData["Message1"]="⇛ Apellido del alumno:"+apellido;
            ViewData["Message2"]="⇛ Cursos elegidos :"+cursos;
            ViewData["Message3"]="⇛ Precio total de créditos :"+precTotalCursos;
            ViewData["Message4"]="⇛ IGV: "+" S/"+IGV+" soles";
            ViewData["Message5"]="⇛ Total a pagar:"+" S/"+total+" soles";

            return View("VistaResultado");
        }

        [HttpGet]

        public ActionResult VistaRegistro(Registro objRegistro)
        {
            var registroCurso = new Registro 
            {
                Courses = new List<Course>
                {
                    new Course{id="1",type="Matemática"},
                    new Course{id="2",type="Lenguaje"},
                    new Course{id="3",type="Historia"},
                }

            };

            return View(registroCurso);

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/RegistroAlumno/VistaRegistro.cshtml
@model Pc1Laboratorio.Models.Registro;

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title></title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>

<body> 
    <marquee SCROLLAMOUNT=18 width=500 direction=left><h1 style="color:#FF8C00;font-family:Comic Sans MS;font-size:100px">
    Bienvenido  
    </h1></marquee>
<br>
   <form asp-controller="RegistroAlumno" asp-action="registrar">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class ="col-sm-6 col-sm-offset-1">
                <b><label asp-for="name" class="control-label"></label></b>
                <input asp-for="name" class="form-control"/>
                <span asp-validation-for="name" class="text-danger" ></span>
            </div>

            <br>

            <div class ="col-sm-6 col-sm-offset-1">
                <b><label asp-for="LastName" class="control-label"></label></b>
                <input asp-for="LastName" class="form-control"/>
                <span asp-validation-for="LastName" class="text-danger" ></span>
            </div>

            <br>

            <div class="form-group">
                <b><label >Course</label></b>
                @for (int i = 0; i < Model.Courses.Count; i++)
                {
                    <div> 
                        @Html.HiddenFor(model => Model.Courses[i].type) 
                        @Html.CheckBoxFor(model => Model.Courses[i].active)
                        @Html.LabelFor(model => Model.Courses[i].active, Model.Courses[i].type)
                    </div> 
                }

            </div>

            <br>

        <button type="submit" class="btn btn-primary" style="color:#0000FF" >Enviar</button>
   </form>

   

   
</body>
</html>

Views/RegistroAlumno/VistaResultado.cshtml
@model Pc1Laboratorio.Models.Registro;

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title></title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body >
  <h1 align="center" style="color:#A52A2A ;font-family:Comic Sans MS">
    Formulario Registrado con éxito
    </h1>

    <br><h3 style="font-family:Lucida Console">@ViewData["Message"]</h3>
    <br><h3 style="font-family:Lucida Console">@ViewData["Message1"]</h3>
    <br><h3 style="font-family:Lucida Console">@ViewData["Message2"]</h3>
    <br><h3 style="font-family:Lucida Console">@ViewData["Message3"]</h3>
    <br><h3 style="font-family:Lucida Console">@ViewData["Message4"]</h3>
    <br><h3 style="font-family:Lucida Console">@ViewData["Message5"]</h3>



</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pc1Laboratorio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pc1Laboratorio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pc1Laboratorio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegistroAlumno" asp-action="VistaRegistro">Registro de alumno</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Pc1Laboratorio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>